/*  Dilip Mahadik, Abhinav - 1002077234
    Misba, Asfiya - 1002028239
    Rajesh Neelam, Haswanth  - 1002063344
    Ponugupati, Maruthi Murali Krishna - 1002069076
    Vyas, Shalini - 1002087896 */

import Chat from "../chat";
import "../css/admin.css";
import Header from "./header_admin";
import SideNav from "./sidenav_admin";

function UserPermissionAdmin() {
  return (
    <div>
      <Header />
      <SideNav />
      <h1 className="table-header">User Permission</h1>
      <table id="customers" class="users-table">
        <thead>
          <tr>
            <th>Access Name</th>
            <th>Students</th>
            <th>Instructors</th>
            <th>QAO</th>
            <th>Program Coordinator</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Exams</td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
          </tr>
          <tr>
            <td>Courses</td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
          </tr>
          <tr>
            <td>Grades</td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
          </tr>
          <tr>
            <td>Attendance</td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
          </tr>
          <tr>
            <td>Messaging</td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
          </tr>
          <tr>
            <td>Reports</td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                defaultChecked={true}
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
          </tr>
          <tr>
            <td>Issue Resolution</td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
            <td>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              />
            </td>
          </tr>
        </tbody>
      </table>

      <Chat />
    </div>
  );
}

export default UserPermissionAdmin;
